session_name: Dotfiles
start_directory: ~/.dotfiles
windows:
  - window_name: .dotfiles
    panes:
      - shell_command:
          - cmd: "c"
  - window_name: Neovim Plugins
    start_directory: "~/.local/share/nvim/lazy"
    panes:
      - shell_command:
          - cmd: "c"
  - window_name: Tmux Plugins
    start_directory: "~/.config/tmux/plugins/tmux-theme"
    panes:
      - shell_command:
          - cmd: "c"
  - window_name: Tmux Fork
    start_directory: "~/Code/catppuccin-tmux/"
    panes:
      - shell_command:
          - cmd: "c"
