session_name: FormFactor
start_directory: ~/Code/form-factor/
windows:
  - window_name: Project
    panes:
      - shell_command:
          - cmd: "c"
  - window_name: Terminals
    panes:
      - shell_command:
          - cmd: "c"
