session_name: NodeSchool
start_directory: ~/Code/node-school/turing-machine/
windows:
  - window_name: TuringMachine
    focus: true
    panes:
      - shell_command:
          - cmd: "c"
  - window_name: Terminals
    panes:
      - shell_command:
          - cmd: "c"
