session_name: Notes
windows:
  - window_name: Loop
    start_directory: "~/Documents/Neorg/"
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: Standards
    start_directory: "~/Code/technical-docs/"
    panes:
      - shell_command:
        - cmd: 'c'
