session_name: Notes
start_directory: "~/Code/notes"
windows:
  - window_name: Work
    start_directory: "~/Code/notes/work/"
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: Personal
    start_directory: "~/Code/notes/personal/"
    panes:
      - shell_command:
        - cmd: 'c'
