session_name: Suralink
start_directory: "~/Code/suralink/"
windows:
  - window_name: Root
    panes:
      - shell_command:
          - cmd: "c"
  - window_name: Admin
    panes:
      - shell_command:
          - cmd: "c"
  - window_name: Frontend
    panes:
      - shell_command:
          - cmd: "c"
  - focus: 'true'
    layout: 535f,249x54,0,0{124x54,0,0,28,124x54,125,0[124x27,125,0,30,124x26,125,28{62x26,125,28,29,61x26,188,28,40}]}
    options: {}
    panes:
    - shell_command:
      - lzd
    - shell_command: cd ./auditManager/ClientApp/npm
    - cd ./auth_accounts
    - focus: 'true'
      shell_command:
        - cd ./auditManager/ClientApp/npm
        - sudo sysctl -p
    window_name: Terminals
