export PATH="/usr/local/opt/php@8.0/bin:$PATH"
export PATH="/usr/local/opt/php@8.0/sbin:$PATH"
export PATH="$PATH:/Applications/XAMPP/bin;yarn global bin;"
export PATH="/Applications/PhpStorm.app/Contents/bin:$PATH"
export PATH="/usr/local/opt/avr-gcc@7/bin:$PATH"
export PATH="$PATH:$HOME/.config/git-commands"
