background        = 0xff1e1e2e
base              = 0xff1e1e2e
text              = 0xffcdd6f4
alternate_base    = 0xff89b4fa
bright_text       = 0xffeff1f5
accent            = 0xff89b4fa
accent_secondary  = 0xff89b4fa

font_size              = 12
small_font_size        = 10
h1_size                = 24
h2_size                = 16
h3_size                = 12
font_family            = Sans Serif
font_family_monospace  = Maple Mono NF
icon_theme             =
rounding_large         = 0
rounding_small         = 0
