export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.config/bin/docker:$PATH"
export PATH="$HOME/.config/bin/git:$PATH"
export PATH="$HOME/.config/bin/node:$PATH"
export PATH="$HOME/.config/bin:$PATH"
export PATH="$HOME/.docker/cli-plugins:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"
export PATH="$HOME/.luarocks/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="/Applications/PhpStorm.app/Contents/bin:$PATH"
export PATH="/home/linuxbrew/.linuxbrew/bin/:$PATH"
export PATH="/opt/homebrew/opt/arm-gcc-bin@8/bin:$PATH"
export PATH="/opt/homebrew/opt/arm-none-eabi-gcc@8/bin:$PATH"
export PATH="/opt/homebrew/opt/avr-gcc@8/bin:$PATH"
export PATH="yarn global bin:$PATH"

export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH

export XDG_DATA_DIRS="$HOME/.local/xdg:$XDG_DATA_DIRS"
export XDG_DATA_DIRS="/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"
export XDG_DATA_DIRS="/var/lib/flatpak/exports/bin:$XDG_DATA_DIRS"
export XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:$XDG_DATA_DIRS"
