[secrets.git]
  username = "op://7sdgfnrg2ads2fqxnqyu63h3ve/6uxtcqnate2wx4si4naaew6mwa/username"
  email = "op://7sdgfnrg2ads2fqxnqyu63h3ve/6uxtcqnate2wx4si4naaew6mwa/personal_email"
  work_email = "op://7sdgfnrg2ads2fqxnqyu63h3ve/6uxtcqnate2wx4si4naaew6mwa/work_email"
