[secrets.git]
  username = "op://7sdgfnrg2ads2fqxnqyu63h3ve/6uxtcqnate2wx4si4naaew6mwa/username"
  personal_email = "op://7sdgfnrg2ads2fqxnqyu63h3ve/6uxtcqnate2wx4si4naaew6mwa/personal_email"
  work_email = "op://7sdgfnrg2ads2fqxnqyu63h3ve/6uxtcqnate2wx4si4naaew6mwa/work_email"

[secrets.zima]
  ip = "op://uk3qacp4wt5hox3vcexed3ffvy/vjih4b2oltomszi354ulcv66da/ip"
  username = "op://uk3qacp4wt5hox3vcexed3ffvy/vjih4b2oltomszi354ulcv66da/username"
  password = "op://uk3qacp4wt5hox3vcexed3ffvy/vjih4b2oltomszi354ulcv66da/password"

[secrets.espanso]
  work_domain = "op://7sdgfnrg2ads2fqxnqyu63h3ve/tmjuq4qzf3nfktdklmdctiwnua/WorkDomain"
  manager_email = "op://7sdgfnrg2ads2fqxnqyu63h3ve/tmjuq4qzf3nfktdklmdctiwnua/ManagerEmail"
  my_email = "op://7sdgfnrg2ads2fqxnqyu63h3ve/tmjuq4qzf3nfktdklmdctiwnua/MyEmail"
  jira_link = "op://7sdgfnrg2ads2fqxnqyu63h3ve/tmjuq4qzf3nfktdklmdctiwnua/JiraLink"
